version: "3.3"

services:
  parser:
    build: .
    container_name: cryptoslate-parser
    environment:
      - NODE_ENV=production
      - MONGODB_HOST=host.docker.internal
      - MONGODB_PORT=27018
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - IMGBB_API_KEY=${IMGBB_API_KEY}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - mongodb_network

networks:
  mongodb_network:
    name: mongodb_network
    driver: bridge
