import axios from 'axios';

export class ChatGPTService {
  private apiKey: string;
  private apiUrl: string;

  constructor() {
    this.apiKey = process.env.OPENAI_API_KEY || '';
    this.apiUrl = 'https://api.openai.com/v1/chat/completions';
  }

  async summarizeForTelegram(content: string): Promise<string> {
    const systemPrompt =
      'You are a professional writer and editor, a native Russian speaker with a good understanding of the nuances of the Russian language, tone and style, specializing in creating short summaries of long texts while preserving the key points and the main idea of the original text. Your task is to make the text generated by artificial intelligence sound natural and human while preserving the main idea of the text';

    const userPrompt = `
      Перед тобой текст, сгенерированный нейросетью. Твоя задача:
      1. Переписать его, чтобы он звучал естественно и по-человечески
      2. Исправить все языковые неточности и стилистические ошибки
      3. Сократить до формата Telegram-поста (максимум 4000 символов)
      4. Сохранить ключевые мысли и основной посыл
      5. Вернуть текст в формате HTML. Используй только теги <h1-6>, <p>, <b>, <i>, <em>, <strong>.
      
      Текст для обработки:
      ${content}
    `;

    const response = await axios.post(
      this.apiUrl,
      {
        model: 'gpt-4',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt },
        ],
      },
      {
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${this.apiKey}`,
        },
      },
    );

    return response.data.choices[0].message.content
      .replace(/^```html\n/, '')
      .replace(/\n```$/, '');
  }
}
